<?php

use Carbon\Carbon;

$date = Carbon::createFromDate(2024, 12, 31)->format('Y-m-d');
$part_reading_mark = 10;
$part_writing_mark = 8;
return [
    'YEAR_WEEKS' => array(
        array('title' => 'الأول من يناير', 'date' => '2025-01-05', 'is_vacation' => 0, 'week_key' => 52),
        array('title' => 'الثاني من يناير', 'date' => '2025-01-12', 'is_vacation' => 0, 'week_key' => 53),
        array('title' => 'الثالث من يناير', 'date' => '2025-01-19', 'is_vacation' => 0, 'week_key' => 54),
        array('title' => 'الرابع من يناير', 'date' => '2025-01-26', 'is_vacation' => 0, 'week_key' => 55),
        array('title' => 'الأول من فبراير', 'date' => '2025-02-02', 'is_vacation' => 0, 'week_key' => 56),
        array('title' => 'الثاني من فبراير', 'date' => '2025-02-09', 'is_vacation' => 0, 'week_key' => 57),
        array('title' => 'الثالث من فبراير', 'date' => '2025-02-16', 'is_vacation' => 0, 'week_key' => 58),
        array('title' => 'الرابع من فبراير', 'date' => '2025-02-23', 'is_vacation' => 0, 'week_key' => 59),
        array('title' => 'الأول من مارس', 'date' => '2025-03-02', 'is_vacation' => 0, 'week_key' => 60),
        array('title' => 'الثاني من مارس', 'date' => '2025-03-09', 'is_vacation' => 0, 'week_key' => 61),
        array('title' => 'الثالث من مارس', 'date' => '2025-03-16', 'is_vacation' => 0, 'week_key' => 62),
        array('title' => 'الرابع من مارس', 'date' => '2025-03-23', 'is_vacation' => 0, 'week_key' => 63),
        array('title' => 'الخامس من مارس', 'date' => '2025-03-30', 'is_vacation' => 0, 'week_key' => 64),
        array('title' => 'الأول من أبريل', 'date' => '2025-04-06', 'is_vacation' => 0, 'week_key' => 65),
        array('title' => 'الثاني من أبريل', 'date' => '2025-04-13', 'is_vacation' => 0, 'week_key' => 66),
        array('title' => 'الثالث من أبريل', 'date' => '2025-04-20', 'is_vacation' => 0, 'week_key' => 67),
        array('title' => 'الرابع من أبريل', 'date' => '2025-04-27', 'is_vacation' => 0, 'week_key' => 68),
        array('title' => 'الأول من مايو', 'date' => '2025-05-04', 'is_vacation' => 0, 'week_key' => 69),
        array('title' => 'الثاني من مايو', 'date' => '2025-05-11', 'is_vacation' => 0, 'week_key' => 70),
        array('title' => 'الثالث من مايو', 'date' => '2025-05-18', 'is_vacation' => 0, 'week_key' => 71),
        array('title' => 'الرابع من مايو', 'date' => '2025-05-25', 'is_vacation' => 0, 'week_key' => 72),
        array('title' => 'الأول من يونيو', 'date' => '2025-06-01', 'is_vacation' => 0, 'week_key' => 73),
        array('title' => 'الثاني من يونيو', 'date' => '2025-06-08', 'is_vacation' => 0, 'week_key' => 74),
        array('title' => 'الثالث من يونيو', 'date' => '2025-06-15', 'is_vacation' => 0, 'week_key' => 75),
        array('title' => 'الرابع من يونيو', 'date' => '2025-06-22', 'is_vacation' => 0, 'week_key' => 76),
        array('title' => 'الخامس من يونيو', 'date' => '2025-06-29', 'is_vacation' => 0, 'week_key' => 77),
        array('title' => 'الأول من يوليو', 'date' => '2025-07-06', 'is_vacation' => 0, 'week_key' => 78),
        array('title' => 'الثاني من يوليو', 'date' => '2025-07-13', 'is_vacation' => 0, 'week_key' => 79),
        array('title' => 'الثالث من يوليو', 'date' => '2025-07-20', 'is_vacation' => 0, 'week_key' => 80),
        array('title' => 'الرابع من يوليو', 'date' => '2025-07-27', 'is_vacation' => 0, 'week_key' => 81),
        array('title' => 'الأول من أغسطس', 'date' => '2025-08-03', 'is_vacation' => 0, 'week_key' => 82),
        array('title' => 'الثاني من أغسطس', 'date' => '2025-08-10', 'is_vacation' => 0, 'week_key' => 83),
        array('title' => 'الثالث من أغسطس', 'date' => '2025-08-17', 'is_vacation' => 0, 'week_key' => 84),
        array('title' => 'الرابع من أغسطس', 'date' => '2025-08-24', 'is_vacation' => 0, 'week_key' => 85),
        array('title' => 'الخامس من أغسطس', 'date' => '2025-08-31', 'is_vacation' => 0, 'week_key' => 86),
        array('title' => 'الأول من سبتمبر', 'date' => '2025-09-07', 'is_vacation' => 0, 'week_key' => 87),
        array('title' => 'الثاني من سبتمبر', 'date' => '2025-09-14', 'is_vacation' => 0, 'week_key' => 88),
        array('title' => 'الثالث من سبتمبر', 'date' => '2025-09-21', 'is_vacation' => 0, 'week_key' => 89),
        array('title' => 'الرابع من سبتمبر', 'date' => '2025-09-28', 'is_vacation' => 0, 'week_key' => 90),
        array('title' => 'الأول من أكتوبر', 'date' => '2025-10-05', 'is_vacation' => 0, 'week_key' => 91),
        array('title' => 'الثاني من أكتوبر', 'date' => '2025-10-12', 'is_vacation' => 0, 'week_key' => 92),
        array('title' => 'الثالث من أكتوبر', 'date' => '2025-10-19', 'is_vacation' => 0, 'week_key' => 93),
        array('title' => 'الرابع من أكتوبر', 'date' => '2025-10-26', 'is_vacation' => 0, 'week_key' => 94),
        array('title' => 'الأول من نوفمبر', 'date' => '2025-11-02', 'is_vacation' => 0, 'week_key' => 95),
        array('title' => 'الثاني من نوفمبر', 'date' => '2025-11-09', 'is_vacation' => 0, 'week_key' => 96),
        array('title' => 'الثالث من نوفمبر', 'date' => '2025-11-16', 'is_vacation' => 0, 'week_key' => 97),
        array('title' => 'الرابع من نوفمبر', 'date' => '2025-11-23', 'is_vacation' => 0, 'week_key' => 98),
        array('title' => 'الخامس من نوفمبر', 'date' => '2025-11-30', 'is_vacation' => 0, 'week_key' => 99),
        array('title' => 'الأول من ديسمبر', 'date' => '2025-12-07', 'is_vacation' => 0, 'week_key' => 100),
        array('title' => 'الثاني من ديسمبر', 'date' => '2025-12-14', 'is_vacation' => 0, 'week_key' => 101),
        array('title' => 'الثالث من ديسمبر', 'date' => '2025-12-21', 'is_vacation' => 0, 'week_key' => 102),
        array('title' => 'الرابع من ديسمبر', 'date' => '2025-12-28', 'is_vacation' => 0, 'week_key' => 103),
    ),
    'SUPPORT_MARK' => 10,
    'PART_READING_MARK' => $part_reading_mark,
    'PART_WRITING_MARK' => $part_writing_mark,
    'FULL_READING_MARK' => 50,
    'FULL_WRITING_MARK' => 40,
    "COMPLETE_THESIS_LENGTH" => 400,
    'ACCEPTED_STATUS' => 'accepted',
    'REJECTED_STATUS' => 'rejected',
    'PENDING_STATUS' => 'pending',
    'FINISHED_STATUS' => 'finished',
    'CANCELED_STATUS' => 'cancelled',
    'REJECTED_WRITING_STATUS' => 'rejected_writing',
    'ACCEPTED_ONE_THESIS_STATUS' => 'accepted_one_thesis',
    'REJECTED_PARTS_STATUS' => 'rejected_parts',
    'FREEZE_THIS_WEEK_TYPE' => 'تجميد الحالي',
    'FREEZE_NEXT_WEEK_TYPE' => 'تجميد القادم',
    'EXCEPTIONAL_FREEZING_TYPE' => 'تجميد استثنائي',
    'EXAMS_MONTHLY_TYPE' => 'نظام امتحانات - شهري',
    'EXAMS_SEASONAL_TYPE' => 'نظام امتحانات - فصلي',
    'WITHDRAWN_TYPE' => 'انسحاب مؤقت',
    'ARABIC_ROLES' => [
        'support_leader' => 'قائد دعم',
        'ambassador' => "سفير",
        'leader' => "قائد",
        'supervisor' => "مراقب",
        'advisor' => 'موجه',
        'consultant' => 'مستشار',
        'admin' => 'ادارة',
        'eligible_admin' => "مسؤول توثيق الكتب",
        'reviewer' => "مراجع توثيق",
        'auditor' => "مُقيم توثيق",
        'super_auditer' => "مسؤول تقييم التوثيقات",
        'super_reviewer' => "مسؤول مراجعة التوثيقات",
        'user_accept' => "مسؤول الوثائق",
        'marathon_coordinator' => "مسؤول عام في مارثون أصبوحة",
        'marathon_verification_supervisor' => "مسؤول تدقيق مارثون أصبوحة",
        'marathon_supervisor' => "مسؤول في مارثون أصبوحة",
        'marathon_ambassador' => "سفير مشارك في مارثون أصبوحة",
        'ramadan_coordinator' => "مسؤول فعاليات رمضان",
        'ramadan_hadith_corrector' => "مُصحح  مسابقة حديث",
        'ramadan_fiqh_corrector' => "مًصحح مسابقة فقه",
        'ramadan_tafseer_corrector' => "مُصحح مسابقة تفسير",
        'ramadan_vedio_corrector' => "مُصحح مسابقة التثقيف بالفيديو",
        'special_care_coordinator' => "مسؤول عام لأفرقة الرعاية الخاصة",
        'special_care_supervisor' => "مراقب رعاية خاصة",
        'special_care_leader' => "قائد رعاية خاصة",
        'coordinator_of_withdrawns_team' => "مسؤول فريق المنسحبين",
        'member_of_withdrawns_team' => "عضو في فريق المنسحبين",
        'book_quality_team_coordinator' => "مسؤول فريق جودة الكتب",
        'book_quality_supervisor' => "مشرف جودة الكتب",
        'book_quality_team' => "عضو في فريق جودة الكتب",
        'osboha_support_coordinator' => "مسؤول دعم أصبوحة",
        'osboha_support_member' => "دعم أصبوحة",



    ],
    'FRONT_URL' => 'https://www.platform.osboha180.com',
    'ALL_SUPPER_ROLES' => ['admin', 'consultant', 'advisor', 'supervisor', 'leader'],
    'SUPERVISORANDABOVE_ROLES' => ['supervisor', 'advisor', 'consultant', 'admin'],
    'rolesToRetrieve' => array(
        'leader' => ['ambassador'],
        'supervisor' => ['ambassador', 'leader'],
        'advisor' => ['supervisor', 'support_leader', 'leader', 'ambassador'],
        'consultant' => ['advisor', 'supervisor', 'leader', 'support_leader', 'ambassador'],
        'admin' => ['admin', 'consultant', 'advisor', 'supervisor', 'leader', 'support_leader', 'ambassador', 'book_quality_team'],

    ),
    'ARABIC_MONTHS' => [
        '1' => 'يناير',
        '2' => 'فبراير',
        '3' => 'مارس',
        '4' => 'ابريل',
        '5' => 'مايو',
        '6' => 'يونيو',
        '7' => 'يوليو',
        '8' => 'اغسطس',
        '9' => 'سبتمبر',
        '10' => 'اكتوبر',
        '11' => 'نوفمبر',
        '12' => 'ديسمبر',
    ],
    'ROLES_HIERARCHY' => [
        'eligible_admin' => ['super_reviewer', 'super_auditer', 'user_accept', 'auditor', 'reviewer'],
        'marathon_coordinator' => ['marathon_verification_supervisor', 'marathon_supervisor', 'marathon_ambassador'],
        'ramadan_coordinator' => ['ramadan_hadith_corrector', 'ramadan_fiqh_corrector', 'ramadan_tafseer_corrector', 'ramadan_vedio_corrector'],
        'special_care_coordinator' => ['special_care_supervisor', 'special_care_leader'],
    ],

];
